### ISSUE TITLE
NameError: name 'download' is not defined

### ISSUE THREAD

**Issue by rmdes** [ashim-bhatta/Streamx#1]
First of all thanks for this code, 
I can run the script fine, see the prompt, search a movie, see the results, pick the movie, the quality, but then :

Available Movie Quality:
1. 720p
2. 1080p

Please Enter the index of the quality which you want to stream\download
1

Traceback (most recent call last):
  File "/Streamx/index.py", line 43, in <module>
    main()
  File "/Streamx/index.py", line 40, in main
    handle_movie.handle_movie_stream(user_choice)
  File "/Streamx/movie.py", line 56, in handle_movie_stream
    self.stream(magnet)
  File "/Streamx/movie.py", line 71, in stream
    if not download:
NameError: name 'download' is not defined

No matter if I choose to download or stream I get this error message, any advice to go beyond this ?

**Comment by ashim-bhatta** [comment]
> First of all thanks for this code, I can run the script fine, see the prompt, search a movie, see the results, pick the movie, the quality, but then :
> 
> Available Movie Quality:
> 
> 1. 720p
> 2. 1080p
> 
> Please Enter the index of the quality which you want to stream\download 1
> 
> Traceback (most recent call last): File "/Streamx/index.py", line 43, in main() File "/Streamx/index.py", line 40, in main handle_movie.handle_movie_stream(user_choice) File "/Streamx/movie.py", line 56, in handle_movie_stream self.stream(magnet) File "/Streamx/movie.py", line 71, in stream if not download: NameError: name 'download' is not defined
> 
> No matter if I choose to download or stream I get this error message, any advice to go beyond this ?

I just fixed that issue. I think it will work now, can try again, Thank you

**Comment by rmdes** [comment]
Confirmed, now it works just fine!
Thanks

11 nov. 2021 11:13:20 ashim-bhatta ***@***.***>:

> First of all thanks for this code, I can run the script fine, see the prompt, search a movie, see the results, pick the movie, the quality, but then :
> 
> Available Movie Quality:
> 
1. > 720p
2. > 1080p
